/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UserLibraryManagement */

#ifndef _Included_UserLibraryManagement
#define _Included_UserLibraryManagement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UserLibraryManagement
 * Method:    loadBooks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UserLibraryManagement_loadBooks
  (JNIEnv *, jobject);

/*
 * Class:     UserLibraryManagement
 * Method:    borrowBook
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_UserLibraryManagement_borrowBook
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     UserLibraryManagement
 * Method:    returnBook
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_UserLibraryManagement_returnBook
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     UserLibraryManagement
 * Method:    searchBook
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_UserLibraryManagement_searchBook
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
